// Generated by https://quicktype.io

import { User } from "src/app/auth/interfaces/user.interface";
import { Currency } from "./cripto.interface";
import { TypeTransaction } from "./type-transaction.enum";

export interface Transaction {
  id:     number;
  user:   User;
  coin:   Currency;
  date:   string;
  amount: number;
  type:   TypeTransaction;
}

export interface Coin {
  id:     number;
  name:   string;
  symbol: string;
}


