// Generated by https://quicktype.io

export interface User {
  id?:            number;
  firstName:     string;
  lastName:      string;
  email:         string;
  password:      string;
  country:       string;
  city:          string;
  direccion:     string;
  paymentMethod: string;
  numsTarjeta:   string;
  cvv:           string;
  iban:          String;
  balanceEuros:  number;
  dateOfExpiry:  Date;
}
